version: '3.8'

services:
  postgres:
    image: postgres:16.11-alpine
    container_name: blog-security-postgres
    environment:
      POSTGRES_DB: blog_security
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blog-network

  app:
    build: .
    container_name: blog-security-api
    depends_on:
      - postgres
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      JWT_EXPIRATION: 86400000
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/blog_security
    ports:
      - "8080:8080"
    networks:
      - blog-network

volumes:
  postgres_data:

networks:
  blog-network:
    driver: bridge